// =============================================================================
// src/frontend/bytecode/bytecode-generator.h
// =============================================================================
// BytecodeGenerator: compiles an AST into a BytecodeProgram.
//
// One FunctionInfo is produced per JS function (plus one for the top-level
// program). The generator performs:
//   - Scope analysis (variable resolution, closure capture detection).
//   - Register allocation: each local variable and temporary gets a slot
//     in the function's register file. Parameters come in slots 0..N-1.
//   - Bytecode emission: walks the AST and emits bytecode for each node.
//   - Jump patching: forward jumps are emitted with a placeholder offset,
//     then patched once the target offset is known.
//
// The generated bytecode is register-based: most operations read from and
// write to the accumulator (a virtual register), with explicit Star/Ldar
// to spill to / load from named registers. This matches the design in
// bytecode.h.
//
// Closure capture:
//   When a function references a variable declared in an enclosing function,
//   the variable moves from a register to a Context slot. The function
//   prologue emits CreateContext + PushContext, and StaContext/LoadContext
//   bytecodes are used to access captured variables through the context
//   chain.

#ifndef V12_FRONTEND_BYTECODE_BYTECODE_GENERATOR_H_
#define V12_FRONTEND_BYTECODE_BYTECODE_GENERATOR_H_

#include <cstdint>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include "base/arena.h"
#include "base/macros.h"
#include "base/small-vector.h"
#include "frontend/ast/ast.h"
#include "frontend/bytecode/bytecode.h"
#include "frontend/bytecode/scope.h"

namespace v12 {

class Isolate;

class BytecodeGenerator {
public:
    BytecodeGenerator(Isolate* iso, Arena* arena);
    ~BytecodeGenerator();

    // Compile a Program AST into a BytecodeProgram. Returns a freshly
    // allocated program (owned by the caller via unique_ptr).
    std::unique_ptr<BytecodeProgram> Compile(Program* prog);

    // Lazily compile a function that was deferred during initial compilation.
    // Called by the interpreter on first CreateClosure for a function with
    // is_compiled == false. Compiles the bytecode into the existing
    // FunctionInfo (in place).
    // The program must be the BytecodeProgram that owns fi and scope_analyzer.
    void CompileLazyFunction(FunctionInfo* fi, BytecodeProgram* program,
                            ScopeAnalyzer* scope_analyzer);

private:
    // ----- Per-function emission state -----
    struct FnState {
        FunctionInfo* info;
        Scope* scope;
        // The register that holds the current Context pointer (or kInvalidReg
        // if there is no context for this function).
        uint8_t context_reg = 0xFF;
        // Stack of loop contexts (for break/continue jump patching).
        struct LoopCtx {
            std::vector<uint32_t> breaks;      // jump offsets to patch
            std::vector<uint32_t> continues;   // jump offsets to patch
            uint32_t loop_start;               // offset to jump back to
        };
        std::vector<LoopCtx> loops;
        // Next temporary register to allocate.
        uint8_t next_temp = 0;
    };

    // Allocate a temporary register. The caller is responsible for
    // releasing it (we use a simple bump allocator — temps are released
    // only at function exit).
    uint8_t AllocTemp(FnState* fs);

    // Run a peephole optimization pass over the bytecode. Removes:
    //   - Ldar r; Star r → nop (acc already equals r after Ldar)
    //   - Star r; Ldar r → nop (acc already equals r after Star)
    //   - Jump X; X: → drop the Jump
    //   - LdaUndefined; Return → ReturnUndefined
    // Returns the number of instructions removed.
    size_t PeepholeOptimize(FunctionInfo* fi);

private:

    // Compile a function body. Returns the FunctionInfo.
    FunctionInfo* CompileFunction(FnState* parent_fs,
                                   Scope* fn_scope,
                                   std::string_view name,
                                   SmallVector<Parameter, 4> params,
                                   Stmt* body,
                                   Expr* expr_body,  // for arrow functions
                                   bool is_toplevel);

    // Statement emission. The result of evaluating a statement (if any) is
    // left in the accumulator.
    void EmitStmt(FnState* fs, Stmt* s);
    void EmitBlock(FnState* fs, Block* b);

    // Expression emission. The result is left in the accumulator.
    void EmitExpr(FnState* fs, Expr* e);

    // Helpers for emitting bytecode bytes.
    void EmitByte(FnState* fs, uint8_t b);
    void EmitOp(FnState* fs, Op op);
    void EmitReg(FnState* fs, Reg r);
    void EmitImm8(FnState* fs, uint8_t v);
    void EmitImm16(FnState* fs, uint16_t v);
    void EmitImm32(FnState* fs, uint32_t v);
    void EmitIdx(FnState* fs, uint16_t idx);   // feedback slot index (imm16)

    // Emit a forward jump, returning the offset of the jump target field
    // (so it can be patched later via PatchJump).
    uint32_t EmitJump(FnState* fs, Op op);
    void PatchJump(FnState* fs, uint32_t patch_offset, uint32_t target_offset);

    uint32_t Here(FnState* fs) const { return static_cast<uint32_t>(fs->info->bytecode.size()); }

    // Constant pool / name table accessors.
    uint32_t AddConstSmi(FnState* fs, intptr_t v);
    uint32_t AddConstNumber(FnState* fs, double v);
    uint32_t AddConstString(FnState* fs, std::string_view s);
    uint32_t AddConstFunctionInfo(FnState* fs, FunctionInfo* fi);
    uint16_t AddPropertyName(FnState* fs, std::string_view s);
    uint16_t AddGlobalName(FnState* fs, std::string_view s);

    // Allocate a feedback slot. For now we just bump a counter — actual
    // feedback collection is a future task (the interpreter treats every
    // feedback slot as a no-op).
    uint16_t AllocFeedbackSlot(FnState* fs) {
        uint16_t s = fs->info->feedback_vector_length++;
        return s;
    }

    // Emit code to load an Identifier. Handles local/context/global resolution.
    void EmitLoadIdentifier(FnState* fs, Identifier* id);
    // Emit code to store the accumulator into an Identifier (assignment).
    void EmitStoreIdentifier(FnState* fs, Identifier* id);

    Isolate* iso_;
    Arena* arena_;
    // The program being compiled. In Compile(), we create a new one and
    // transfer ownership to the caller. In CompileLazyFunction, we borrow
    // the existing program (non-owning).
    // IMPORTANT: program_owned_ must be declared BEFORE program_raw_
    // because program_raw_ is initialized from program_owned_.get() in
    // the constructor's initializer list, and C++ initializes members in
    // declaration order.
    std::unique_ptr<BytecodeProgram> program_owned_;
    BytecodeProgram* program_raw_ = nullptr;
    // The scope analyzer. Owned by Compile() (created via unique_ptr).
    // For lazy compilation, borrowed from the BytecodeProgram.
    std::unique_ptr<ScopeAnalyzer> scope_analyzer_owned_;
    ScopeAnalyzer* scope_analyzer_raw_ = nullptr;
};

}  // namespace v12

#endif  // V12_FRONTEND_BYTECODE_BYTECODE_GENERATOR_H_
